# -*- coding: utf-8 -*-
"""LBM_Lid_Driven.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YyBI--7JrNazBI3pJv-5kN-GiKD4Gzoh
"""

import numpy as np
import matplotlib.pyplot as plt

imax = 51
kp = 9
re = 100
U = 0.1
c_s_square = 1/3
max_iters = 10000

dt = 1/(imax-1)
tau = 0.5*(((6*U)/(re*dt))+1)

u = np.zeros((imax,imax))
v = np.zeros((imax,imax))
u[-1,:] = U
ex = np.array([0, 1, 0, -1, 0, 1, -1, -1, 1])
ey = np.array([0, 0, 1, 0, -1, 1, 1, -1, -1])
w = np.array([16/36, 4/36, 4/36, 4/36, 4/36, 1/36, 1/36, 1/36, 1/36])

rho = np.ones((imax,imax))

def equilibrimfunc(rho,u,v):
  feq = np.zeros((9,imax,imax))
  u_sq = u**2 + v**2
  for i in range(9):
    c = ex[i]*u + ey[i]*v
    feq[i, :, :] = w[i]*rho*(1+3*c+4.5*(c**2)-1.5*u_sq)
  return feq

f = equilibrimfunc(rho,u,v)

for t in range(max_iters):
  feq = equilibrimfunc(rho, u, v)
  f = f-(f-feq)/tau
  for i in range(kp):
      f[i, :, :] = np.roll(np.roll(f[i, :, :], ex[i], axis=1), ey[i], axis=0)

  f[2, 0, :] = f[4, 0, :]
  f[5, 0, :] = f[7, 0, :]
  f[6, 0, :] = f[8, 0, :]

  f[1, :, 0] = f[3, :, 0]
  f[5, :, 0] = f[7, :, 0]
  f[8, :, 0] = f[6, :, 0]

  f[3, :, -1] = f[1, :, -1]
  f[6, :, -1] = f[8, :, -1]
  f[7, :, -1] = f[5, :, -1]

  f[:, -1, :] = equilibrimfunc(np.ones(imax), np.full(imax, U), np.zeros(imax))[:, -1, :]

  rho = np.sum(f, axis=0)
  u = np.zeros((imax, imax))
  v = np.zeros((imax, imax))
  for i in range(9):
      u+=f[i, :, :]*ex[i]
      v+=f[i, :, :]*ey[i]
  u = u/rho
  v = v/rho

plt.figure(figsize=(6, 5))
plt.title(f"Lid-Driven Cavity Velocity Contours (Re={int(re)})")
Y, X = np.mgrid[0:imax, 0:imax]
velocity_mag = np.sqrt(u**2 + v**2)
contour_filled = plt.contourf(X, Y, velocity_mag, levels=20, cmap='jet')
plt.contour(X, Y, velocity_mag, levels=20, colors='black', linewidths=0.5, alpha=0.5)
plt.xlim(0, imax-1)
plt.ylim(0, imax-1)
plt.colorbar(contour_filled, label='Velocity Magnitude')
plt.show()